services:
  fastapi_service:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres:
    env_file:
      - .env
  postgres:
    image: postgres:18
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_DB: gov_check_db
      POSTGRES_USER: govcheck_user
      POSTGRES_PASSWORD: gov_check_pw
      TZ: Europe/Stockholm
      PGTZ: Europe/Stockholm
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped
    network_mode: "host"
