services:
  caddy:
    image: caddy:latest
    ports:
    - "80:80"
    - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - frontend_dist:/srv/frontend:ro
    restart: unless-stopped

  backend:
    profiles:
      - backend
    build: 
      context: .
      target: backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    profiles:
      - frontend
    build: 
      context: ./app/
      target: frontend-build
    env_file:
      - .env
    volumes:
      - frontend_dist:/usr/src/app/dist

  tests:
    profiles:
      - test
    build:
      context: .
      target: test
    depends_on:
      db-test:
        condition: service_healthy
    env_file:
      - .env.test

  db:
    image: pgvector/pgvector:0.8.3-pg18-trixie
    hostname: postgres
    environment:
      POSTGRES_DB: gov_check_db
      POSTGRES_USER: gov_check_user
      POSTGRES_PASSWORD: gov_check_pw
      TZ: Europe/Stockholm
      PGTZ: Europe/Stockholm
    ports:
      - "5432:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d:ro
      - postgres:/var/lib/postgresql
    restart: unless-stopped

  db-test:
    profiles:
      - test
    image: pgvector/pgvector:0.8.3-pg18-trixie
    hostname: postgres-test
    environment:
      POSTGRES_DB: gov_check_db_test
      POSTGRES_USER: gov_check_user
      POSTGRES_PASSWORD: gov_check_pw
      TZ: Europe/Stockholm
      PGTZ: Europe/Stockholm
    ports:
      - "5433:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gov_check_user -d gov_check_db_test"]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  postgres:
  caddy_data:
  caddy_config:
  frontend_dist:
