services:
  app:
    profiles:
      - app
    build: 
      context: .
      target: app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  tests:
    profiles:
      - test
    build:
      context: .
      target: test
    depends_on:
      - db-test
    env_file:
      - .env.test

  db:
    image: pgvector/pgvector:0.8.2-pg18-trixie
    hostname: postgres
    environment:
      POSTGRES_DB: gov_check_db
      POSTGRES_USER: govcheck_user
      POSTGRES_PASSWORD: gov_check_pw
      TZ: Europe/Stockholm
      PGTZ: Europe/Stockholm
    ports:
      - "5432:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d:ro
      - postgres:/var/lib/postgresql
    restart: unless-stopped

  db-test:
    profiles:
      - test
    image: pgvector/pgvector:0.8.2-pg18-trixie
    hostname: postgres
    environment:
      POSTGRES_DB: gov_check_db_test
      POSTGRES_USER: govcheck_user
      POSTGRES_PASSWORD: gov_check_pw
      TZ: Europe/Stockholm
      PGTZ: Europe/Stockholm
    ports:
      - "5432:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d:ro

volumes:
  postgres:
